rm -f how_to_opensource/core.py
rm -f mypy.ini
rm -f how_to_opensource/tests/test_core.py
rm -f .github/workflows/python-package-conda.yml
rm -rf doc
rm -f .readthedocs.yml
rm -f setup.py
rm -f how_to_opensource/_version.py
rm -f .bumpversion.cfg